apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 310
  template:
    spec:
      containers:
      - name: migrate
        image: check-app-backend:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "manage.py", "migrate"]      
      restartPolicy: OnFailure
